export * from './orthography.response'
export * from './pros-cons.response'
export * from './translate'
export * from './sarcastic-mode.response'
export * from  './explain-code.response'
export * from './audio-to-text.response'